import "./globals.css";
import { Header } from "@/components/Header/Header";
import { MainContainer } from "@/shared/components";

export const metadata = {
  title: "My company",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <MainContainer>{children}</MainContainer>
        </main>
      </body>
    </html>
  );
}
